export const createAccountResponse = {
  Name: 'Olufemi Deborah',
  FirstName: null,
  LastName: null,
  Email: null,
  PhoneNo: null,
  Nuban: '1100063634',
  Number: '00750021120006363',
  PhoneNuber: '910281200221',
  BVN: '90130001921',
  AvailableBalance: 0,
  LedgerBalance: 0,
  Status: 'Active',
  Tier: '1',
  MaximumBalance: 0,
  MaximumDeposit: null,
  IsSuccessful: true,
  ResponseMessage: null,
  PNDStatus: 'InActive',
  LienStatus: 'InActive',
  FreezeStatus: 'InActive',
  RequestStatus: true,
  ResponseDescription: 'Successful',
  ResponseStatus: null,
};
