-- CreateEnum
CREATE TYPE "MFAMethod" AS ENUM ('AUTHENTICATOR_APP');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "hasMFAEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mfaMethod" "MFAMethod" NOT NULL DEFAULT 'AUTHENTICATOR_APP';
