export const createCustomerResponse = {
  LastName: 'Test',
  OtherNames: 'Customer',
  Address: 'Yaba, Lagos',
  Gender: 'Male',
  DateOfBirth: '2023-07-31T00:00:00',
  PhoneNo: '09090908989',
  NationalIdentityNo: '56789823543',
  CustomerType: 'Individual',
  BankVerificationNumber: '19087235678',
  CustomerID: '004529',
  Email: 'testcustomer@test.com',
};

export const existsResponse = true;

export const getById = {
  Id: 0,
  customerID: '006363',
  LastName: 'Olufemi',
  Gender: 1,
  GenderString: 'Female',
  OtherNames: 'Deborah',
  Address: 'Lagos',
  Email: 'debooo@gmail.com',
  Landmark: null,
  PhoneNumber: '910281200221',
  NickName: null,
  BankVerificationNumber: '90130001921',
  NationalIdentityNo: null,
  EmailNotification: false,
  PhoneNotification: true,
  DistrictOfResidence: null,
  DistrictOfBusiness: null,
  IdentificationNumber: null,
  DateOfBirth: '1993-06-19T00:00:00',
  HomeTown: null,
  LocalGovernment: null,
  MothersMaidenName: null,
  Nationale: null,
  TestQuestion: null,
  TestAnswer: null,
  State: null,
  WorkAddress: null,
  WorkAnnualIncome: 0,
  WorkEmployerName: null,
  WorkNextOfKin: null,
  WorkNextOfKinAddress: null,
  WorkNextOfKinPhoneNo: null,
  WorkNextOfKinRelationship: null,
  WorkOccupation: null,
  WorkPhoneNo: null,
  NameOnUtilityBill: null,
  AddressOnUtilityBill: null,
  DateOnUtilityBill: null,
  CommentsForUtilityBill: null,
  IsUtilityBillInfoComplete: false,
  NextOfKinEmailAddress: null,
  CustomerPhoto: null,
  CustomerSignature: null,
  Accounts: [
    {
      AccessLevel: '1',
      AccountNumber: '1100063634',
      AccountStatus: 'Active',
      AccountType: 'SavingsOrCurrent',
      AccountBalance: '0.00',
      Branch: null,
      CustomerID: '006363',
      CustomerName: 'Olufemi, Deborah',
      DateCreated: '12/23/2024 10:27:40 AM',
      LastActivityDate: '',
      NUBAN: '1100063634',
      Refree1CustomerID: null,
      Refree2CustomerID: null,
      ReferenceNo: null,
    },
  ],
  Name: null,
  PostalAddress: null,
  BusinessPhoneNo: null,
  TaxIDNo: null,
  BusinessName: null,
  TradeName: null,
  IndustrialSector: null,
  CompanyRegDate: null,
  ContactPersonName: null,
  BusinessType: null,
  BusinessNature: null,
  WebAddress: null,
  DateIncorporated: null,
  BusinessCommencementDate: null,
  RegistrationNumber: null,
  CustomerMembers: null,
  TheDirectors: null,
};

export const getByAccountNumber = {
  address: 'Lagos',
  age: '31',
  BVN: '90130001921',
  branchCode: '002',
  customerID: '006363',
  dateOfBirth: '6/19/1993 12:00:00 AM',
  email: 'debooo@gmail.com',
  gender: 'Female',
  localGovernmentArea: null,
  name: 'Olufemi, Deborah',
  phoneNumber: '910281200221',
  state: null,
  Accounts: [
    {
      accessLevel: '1',
      accountNumber: '00750021120006363',
      accountStatus: 'Active',
      accountType: 'SavingsOrCurrent',
      availableBalance: '0.00',
      branch: 'HUB 1',
      customerID: '006363',
      accountName: 'Olufemi Deborah',
      productCode: '112',
      dateCreated: '12/23/2024 10:27:40 AM',
      lastActivityDate: '',
      ledgerBalance: '0.00',
      NUBAN: '1100063634',
      referenceNo: null,
      withdrawableAmount: '0.00',
      kycLevel: '1',
    },
  ],
  PostalAddress: null,
  BusinessPhoneNo: null,
  TaxIDNo: null,
  BusinessName: null,
  TradeName: null,
  IndustrialSector: null,
  CompanyRegDate: null,
  ContactPersonName: null,
  BusinessType: null,
  BusinessNature: null,
  WebAddress: null,
  DateIncorporated: null,
  BusinessCommencementDate: null,
  RegistrationNumber: null,
  CustomerMembers: null,
  TheDirectors: null,
};

export const getByPhoneNo = [
  {
    Id: 0,
    customerID: '006363',
    LastName: 'Olufemi',
    Gender: null,
    GenderString: null,
    OtherNames: 'Deborah',
    Address: 'Lagos',
    Email: 'debooo@gmail.com',
    Landmark: null,
    PhoneNumber: '910281200221',
    NickName: null,
    BankVerificationNumber: '90130001921',
    NationalIdentityNo: '',
    EmailNotification: false,
    PhoneNotification: true,
    DistrictOfResidence: null,
    DistrictOfBusiness: null,
    IdentificationNumber: null,
    DateOfBirth: '1993-06-19T00:00:00',
    HomeTown: null,
    LocalGovernment: null,
    MothersMaidenName: null,
    Nationale: null,
    TestQuestion: null,
    TestAnswer: null,
    State: null,
    WorkAddress: null,
    WorkAnnualIncome: 0,
    WorkEmployerName: null,
    WorkNextOfKin: null,
    WorkNextOfKinAddress: null,
    WorkNextOfKinPhoneNo: null,
    WorkNextOfKinRelationship: null,
    WorkOccupation: null,
    WorkPhoneNo: null,
    NameOnUtilityBill: null,
    AddressOnUtilityBill: null,
    DateOnUtilityBill: null,
    CommentsForUtilityBill: null,
    IsUtilityBillInfoComplete: false,
    NextOfKinEmailAddress: null,
    CustomerPhoto: null,
    CustomerSignature: null,
    Accounts: [
      {
        AccessLevel: '1',
        AccountNumber: '1100063634',
        AccountStatus: 'Active',
        AccountType: 'SavingsOrCurrent',
        AccountBalance: '0.00',
        Branch: null,
        CustomerID: '006363',
        CustomerName: 'Olufemi, Deborah',
        DateCreated: '12/23/2024 10:27:40 AM',
        LastActivityDate: '',
        NUBAN: '1100063634',
        Refree1CustomerID: null,
        Refree2CustomerID: null,
        ReferenceNo: null,
      },
    ],
    Name: null,
    PostalAddress: null,
    BusinessPhoneNo: null,
    TaxIDNo: null,
    BusinessName: null,
    TradeName: null,
    IndustrialSector: null,
    CompanyRegDate: null,
    ContactPersonName: null,
    BusinessType: null,
    BusinessNature: null,
    WebAddress: null,
    DateIncorporated: null,
    BusinessCommencementDate: null,
    RegistrationNumber: null,
    CustomerMembers: null,
    TheDirectors: null,
  },
];

export const getByBvn = {
  IsSuccessful: true,
  CustomerIDInString: null,
  Message: {
    Id: 0,
    customerID: '006363',
    LastName: 'Olufemi',
    Gender: null,
    GenderString: null,
    OtherNames: 'Deborah',
    Address: 'Lagos',
    Email: 'debooo@gmail.com',
    Landmark: null,
    PhoneNumber: '910281200221',
    NickName: null,
    BankVerificationNumber: '90130001921',
    NationalIdentityNo: null,
    EmailNotification: false,
    PhoneNotification: true,
    DistrictOfResidence: null,
    DistrictOfBusiness: null,
    IdentificationNumber: null,
    DateOfBirth: '1993-06-19T00:00:00',
    HomeTown: null,
    LocalGovernment: null,
    MothersMaidenName: null,
    Nationale: null,
    TestQuestion: null,
    TestAnswer: null,
    State: null,
    WorkAddress: null,
    WorkAnnualIncome: 0,
    WorkEmployerName: null,
    WorkNextOfKin: null,
    WorkNextOfKinAddress: null,
    WorkNextOfKinPhoneNo: null,
    WorkNextOfKinRelationship: null,
    WorkOccupation: null,
    WorkPhoneNo: null,
    NameOnUtilityBill: null,
    AddressOnUtilityBill: null,
    DateOnUtilityBill: null,
    CommentsForUtilityBill: null,
    IsUtilityBillInfoComplete: false,
    NextOfKinEmailAddress: null,
    CustomerPhoto: null,
    CustomerSignature: null,
    Accounts: [
      {
        AccessLevel: '1',
        AccountNumber: '1100063634',
        AccountStatus: 'Active',
        AccountType: 'SavingsOrCurrent',
        AccountBalance: '0.00',
        Branch: null,
        CustomerID: '006363',
        CustomerName: 'Olufemi, Deborah',
        DateCreated: '12/23/2024 10:27:40 AM',
        LastActivityDate: '',
        NUBAN: '1100063634',
        Refree1CustomerID: null,
        Refree2CustomerID: null,
        ReferenceNo: null,
      },
    ],
    Name: null,
    PostalAddress: null,
    BusinessPhoneNo: null,
    TaxIDNo: null,
    BusinessName: null,
    TradeName: null,
    IndustrialSector: null,
    CompanyRegDate: null,
    ContactPersonName: null,
    BusinessType: null,
    BusinessNature: null,
    WebAddress: null,
    DateIncorporated: null,
    BusinessCommencementDate: null,
    RegistrationNumber: null,
    CustomerMembers: null,
    TheDirectors: null,
  },
  TransactionTrackingRef: null,
  Page: null,
};
