export const tinResponse = {
  entity: {
    search: '18609323-0001',
    taxpayer_name: 'BRYAN GODWIN NIG LTD',
    cac_reg_number: '3897612',
    firstin: '18609323-0001',
    jittin: 'N/A',
    tax_office: 'MSTO ALIMOSHO',
    phone_number: '08012345678',
    email: 'test@gmail.com',
  },
};

export const cacBasicResponse = {
  entity: {
    company_name: 'JOHN DOE LIMITED',
    type_of_company: 'BUSINESS_NAME',
    address: '25A James Street Magodo Phase I, Lagos, Nigeria.',
    status: 'Not Active',
    date_of_registration: '2021-03-18T09:53:20.310+00:00',
    rc_number: '1234567',
    business_number: '1234567',
    email: 'ABC@GMAIL.COM',
    state: 'Lagos',
    city: 'Lagos',
    lga: 'Kosofe',
    business: '7a666454-8ce0-44e2-ac32-3e8cb04b6b72',
  },
};

export const cacAdvancedResponse = {
  entity: {
    Branch_Address: 'No 42, Ewegbemi Bustop, Command Road, Lagos State.',
    City: '',
    Classification: 'BUSINESS NAME',
    Date_of_Registration: '2018-09-18T20:57:01.413+00:00',
    Email: '',
    Head_Office_Address: '',
    LGA: 'Alimosho',
    Name_of_Company: 'HAPPY DELI GRILLS',
    Number_of_Affiliates: '1',
    RC_Number: '2653386',
    Share_capital: '',
    Share_capital_in_words: '',
    State: 'LAGOS',
    Status: 'INACTIVE',
    Type_of_Company: 'BUSINESS_NAME',
    affiliates: [
      {
        accreditationnumber: '111111111',
        address: 'No 12, Adejumo Street, Last Bus stop, Meiran, Lagos State. ',
        affiliateType: 'PROPRIETOR',
        city: 'Lagos',
        companyId: 4927923,
        companyName: 'Dojah Inc',
        companyRcNumber: '11111111',
        corporateName: 'Dojah Inc',
        corporateRcNumber: '1111111',
        corporationName: 'Dojah Inc',
        countryName: 'NIGERIA',
        dateOfAppointment: '06-04-2018',
        dateOfBirth: '01-04-1986',
        dateOfTermination: null,
        email: 'olaofeyetunde@yahoo.com',
        firstname: 'Yetunde ',
        formerFirstName: null,
        formerName: null,
        formerNationality: null,
        formerOtherName: null,
        formerSurname: null,
        gender: 'FEMALE',
        id: 11547811,
        identityNumber: 'A25182063',
        identityType: "Permanent Voters' Card",
        isChairman: false,
        isCorporate: false,
        lga: null,
        name: 'Olaofe, Yetunde  Ayobami',
        nationality: 'Nigerian',
        occupation: 'Businesswoman',
        otherDirectorshipDetails: null,
        othername: 'Ayobami',
        phoneNumber: '07068774478',
        postcode: null,
        rcNumber: null,
        searchScore: null,
        shareAllotted: null,
        shareType: null,
        state: 'LAGOS',
        status: 'ACTIVE',
        streetNumber: null,
        surname: 'Olaofe',
        uuid: null,
      },
    ],
    imageReport:
      'https://dojah.s3.us-east-2.amazonaws.com/images/9cb091fe39054148a8e2b07177b7f408.pdf',
  },
};
