export enum CompanyType {
  BUSINESS_NAME = 'BUSINESS_NAME',
  COMPANY = 'COMPANY',
  INCORPORATED_TRUSTESS = 'INCORPORATED_TRUSTESS',
  LIMITED_PARTNERSHIP = 'LIMITED_PARTNERSHIP',
  LIMITED_LIABILITY_PARTNERSHIP = 'LIMITED_LIABILITY_PARTNERSHIP',
}

export enum AdvancedType {
  co = 'co',
  bn = 'bn',
  it = 'it',
}
